### ISSUE TITLE
iOS的还没有完成吧

### ISSUE THREAD

**Issue by ygmpkk** [BuglyDevTeam/Bugly-Flutter-Plugin#1]
刚刚用了一下，再看了一下iOS的channel代码，都是空的

**Comment by zjrwdl** [comment]
> 刚刚用了一下，再看了一下iOS的channel代码，都是空的

已经提交

**Comment by ygmpkk** [comment]
> > 刚刚用了一下，再看了一下iOS的channel代码，都是空的
> 
> 已经提交

好的，辛苦了
