### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (.../ios/Pods/Bugly/Bugly.framework)

### ISSUE THREAD

**Issue by snail-xx** [BuglyDevTeam/Bugly-Flutter-Plugin#5]
#### flutter 工程添加依赖后， `pod install`时出现如下错误：
![image](https://user-images.githubusercontent.com/25047597/90133687-82602180-dda2-11ea-8a42-bf60ddc72406.png)

Google搜索一番后，好像是 [这个原因](https://github.com/flutter/flutter/issues/14161#issuecomment-358607554) 引起的。

经过测试在podspecs 中加上` s.static_framework = true` 后，可解决该问题。

**Comment by zjrwdl** [comment]
0.0.6已经修复https://pub.dev/packages/bugly_crash/install
