### ISSUE TITLE
Bugly应用升级502报错

### ISSUE THREAD

**Issue by zhuxiangqing** [BuglyDevTeam/Bugly-Flutter-Plugin#7]
不分设备型号
<img width="906" alt="WeChata2f63580e7aaa761b5d3a183a883e2c6" src="https://user-images.githubusercontent.com/18080291/103549952-25950d00-4ee3-11eb-97b0-c4dba24e8998.png">

http://android.bugly.qq.com/rqd/async?aid=2c578147-cf2b-4f7a-9906-7142063d59f4
502

从1月2号开始的

appid: 93904d31b6

**Comment by zjrwdl** [comment]
这个插件不支持app升级功能 ， 只支持error 和 crash 监控上报https://pub.dev/packages/bugly_crash/install
